### PR TITLE
added day 1 notes

### PR DESCRIPTION
**Pull request by dlebauer**
@klajbor2 please review and update as appropriate. 

I can recompile to the website or see the README if you are feeling adventurous. (I've compiled the current version of these files, but would appreciate if you could flush them out and add anything that is missing).

### CODE REVIEW

**Comment by dlebauer** [comment]
I randomly selected three reviewers ... please let me know if there are gaps that should be filled. Note that these are 'notes' not 'lessons'. They can be previewed here: https://pi4-uiuc.github.io/2017-bootcamp/post/

**Comment by klajbor2** [comment]
I've committed some edits on the day 1 notes about the terminal shell. I stuck to the principle that these are notes capturing what was discussed.

@rjunior911 , @wlinz , and @kaduran2 : please check if anything is unclear in the day 1 notes about the shell.

**Review by wlinz — COMMENTED** [review]
On the whole, very comprehensible (though there are a number of small typos throughout the document). About line 166 in the Terminal/Unix shell: if the goal is to get crop data/yield trait, should the "echo" command be there?

**Comment by dlebauer** [comment]
@klajbor2 thanks for your revisions and for adding so much additional context and background information.

@wlinz thanks for your review - you were correct about the use of 'echo' in the script. I've changed it.

**Comment by klajbor2** [comment]
@wlinz thanks for the review. btw there is a cool feature on here to comment specific lines of code, under the "files changed" tab you can hover over the left of the line of code until you see a blue square, clicking on that allows you to comment on a specific line

@dlebauer no problem, I'm working on the git notes next

**Comment by klajbor2** [comment]
I've edited the version control notes with commit 6fa2e99.

@rjunior911 @wlinz @kaduran2 : please check for typos, clarity, and any feedback you think might be useful

@dlebauer I've included the html built from the Rmd using RStudio

**Comment by dlebauer** [comment]
Awesome, thanks @klajbor2 !

**Comment by kaduran2** [comment]
Directions in the notes are clear and easy to follow. Explanation of terms is sufficiently detailed for the majority, but some particular areas where more explanation might be useful:
-what should the reader expect "curl" to do? The first instance is in a block of example text in the Useful Tools section.
-in the sed section, what is the significance of "s/" and "/g"?
-in the Shell Scripts section, what specifically does "chmod" do in general?

**Pull request merged**
